language: java
dist: trusty
sudo: false
jdk:
  - oraclejdk8
addons:
  sonarcloud:
    organization: "servicospringintegration"
    token:
      secure: "$SONAR_KEY"
script:
    - mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.4.0.905:sonar
    #- sonar-scanner
   #- mvn clean install
   #- mvn sonar:sonar
deploy:
 provider: heroku
 api-key:
  secure: $SONAR_HEROKU
 app: servicospringintegration
